### PR TITLE
add possibility to add objects during runtime

### PR DESCRIPTION
**Pull request by NeumannM89**

### CODE REVIEW

**Comment by andreihaidu** [comment]
@NeumannM89 it does not really make sense to add a hard dependency on the slicing component, since the tf is not really related to it. It would make sense the other way around, the slicing logic to depend on the tf module and to update the tf manager through a direct call.

**Comment by NeumannM89** [comment]
@andreihaidu Thats why I added the #with_slicing to the code. If someone does not want to use slicing they can comment it in the build.cs. The reason we wanted to use it this way is because slicing broadcast the creation of a new slice so we could use this.

**Comment by andreihaidu** [comment]
@NeumannM89 you mean than it would be fine to have for every use case a new pull request with a preprocessors flags in the code? As you mentioned in the comment, you wanted to use it because the slicing broadcasts the creation of a new slice, so you have the logic happening in slicing, which can easily delegate an update call to the tf manager.

**Comment by NeumannM89** [comment]
@andreihaidu thats true. Than we can close this request. If your suggestions are implement, we can make a new pull request.

**Pull request closed without merging**
